spring:
  application:
    name: Order Endpoint REST
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/orders-database
    username: orders-database
    password: orders-database

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

logging:
  level:
    ROOT: INFO
    org.springframework.data.repository: INFO
    org.hibernate: INFO
